import "./globals.css";
import { Poppins, Raleway } from "next/font/google";

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
});

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        cz-shortcut-listen="true"
        className={`${poppins.variable} ${raleway.variable} overflow-x-hidden antialiased xl:w-[100vw]`}
      >
        {children}
      </body>
    </html>
  );
}
